### ISSUE TITLE
pre-push hook

### ISSUE THREAD

**Issue by furanzujin** [r2d2bzh/js-rules#3]
The first command used in the pre-push hook is supposed to check whether the current branch name starts with a `wip/` path or not.
Though an error is raised when it is executed (see hereafter snippet).

``` shell
❯ npx --no-install r2d2bzh-js-rules isWIP
r2d2bzh-js-rules isWIP

Check if the current branch name reflects a work in progress

Options:
  --version  Show version number     [boolean]
  --help     Show help               [boolean]

TypeError: Cannot read properties of undefined (reading 'replace')
    at normalizePath (/home/username/dev/services/project-name/node_modules/isomorphic-git/index.cjs:1347:6)
    at Array.map (<anonymous>)
    at join (/home/username/dev/services/project-name/node_modules/isomorphic-git/index.cjs:1360:30)
    at currentBranch (/home/username/dev/services/project-name/node_modules/isomorphic-git/index.cjs:7983:12)
    at default (file:///home/username/dev/services/project-name/node_modules/@r2d2bzh/js-rules/is-wip.js:6:54)
    at Object.handler (file:///home/username/dev/services/project-name/node_modules/@r2d2bzh/js-rules/bin.js:11:31)
    at file:///home/username/dev/services/project-name/node_modules/yargs/build/lib/command.js:215:54
    at maybeAsyncResult (file:///home/username/dev/services/project-name/node_modules/yargs/build/lib/utils/maybe-async-result.js:9:15)
    at CommandInstance.applyMiddlewareAndGetResult (file:///home/username/dev/services/project-name/node_modules/yargs/build/lib/command.js:214:25)
    at CommandInstance.runCommand (file:///home/username/dev/services/project-name/node_modules/yargs/build/lib/command.js:128:20)
```

**Comment by gautaz** [comment]
Thanks for the issue.

I've just fixed this in d1b982d and it has been [published](https://www.npmjs.com/package/@r2d2bzh/js-rules/v/0.8.1).
